stages:
- deploy

release:
  stage: deploy
  script:
    - pip install poetry twine
    - poetry version minor # Should use an environment variable rather than hardcoding "minor" version bumps.
    - poetry build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  rules: 
  - if: $mode == "release"
    when: always
