stages:
- deploy

publish:
  stage: deploy
  image: python:3.10
  rules: 
  - if: $CI_COMMIT_TAG
  variables:
    POETRY_REPOSITORIES_GITLAB_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
    POETRY_HTTP_BASIC_GITLAB_USERNAME: "gitlab-ci-token"
    POETRY_HTTP_BASIC_GITLAB_PASSWORD: ${CI_JOB_TOKEN}
  script:
    - pip install poetry
    - poetry self add "poetry-dynamic-versioning[plugin]"
    - poetry build
    - poetry publish --repository gitlab