[tool.poetry]
name = "tap-bamboohr"
version = "0.0.1"
description = "`tap-bamboohr` is Singer-compliant BambooHR tap built with Singer SDK."
authors = ["Derek Visch <dvisch@autoidm.com>"]
license = "Apache v2"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
requests = "^2.25.1"
singer-sdk = "^0.53.4"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
tox = "^4.0.0"
flake8 = "^7.0.0"
ruff = "^0.8.0"
black = "^24.0.0"
pydocstyle = "^6.3.0"
mypy = "^1.0.0"
types-requests = "^2.31.0"
isort = "^5.13.0"

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_bamboohr"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-bamboohr = 'tap_bamboohr.tap:cli'
